# data
datafile: 'processed_data/covs_mats_30min_19_22.h5' #_reduced20pct
root: 'processed_data/cached_covs_mats_30min_19_22'
split_proportion: 0.8 # to be modified



# model
train: True
modelname: 'RGNN_PriceCov'
seq_length: 10
batch_size: 128
num_features: 1
hidden_channels: 64
num_heads: 2
output_edge_channels: 1
output_node_channels: 1
learning_rate: 0.0001
num_epochs: 25
tolerance: 1e-5
